name: CI
on:
  pull_request:
    branches: [main]
  schedule: [cron: "0 */4 * * *"]

jobs:
  build-latest-stable-kernel:
    name: Build latest stable kernel with LLVM 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          curl http://cdn.kernel.org -o kernel.org.html
          sed -n '/<td>stable:<\/td>/I,/<\/tr>/I{ s/<[^>]*>//g; s/\[[^][]*\]//g; p }' kernel.org.html > stable_info.txt
          grep -E "[0-9]+\.[0-9]+" stable_info.txt > stable_versions.txt
          KERNEL_VERSION=`awk 'NR==1 {print $1}' stable_versions.txt`
          echo "To compile kernel $KERNEL_VERSION"
          build/build-kernel.sh
        env:
          LLVM_VERSION: 10
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-previous-stable-kernel:
    name: Build previous stable kernel with LLVM 9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          curl http://cdn.kernel.org -o kernel.org.html
          sed -n '/<td>stable:<\/td>/I,/<\/tr>/I{ s/<[^>]*>//g; s/\[[^][]*\]//g; p }' kernel.org.html > stable_info.txt
          grep -E "[0-9]+\.[0-9]+" stable_info.txt > stable_versions.txt
          KERNEL_VERSION=`awk 'NR==2 {print $1}' stable_versions.txt`
          echo "To compile kernel $KERNEL_VERSION"
          build/build-kernel.sh
        env:
          LLVM_VERSION: 9
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-image:
    name: Build OS image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - run: |
          build/build-os-image.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-mini-linux:
    name: Build mini linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          build/build-mini-linux.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  #build-crosstool-ng:
  #  name: Build crosstool-NG
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: |
  #        build/build-crosstool-ng.sh
  #    - name: Setup tmate session
  #      if: ${{ failure() }}
  #      uses: mxschmitt/action-tmate@v3

  #qemu-test:
  #  name: QEMU test
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Setup tmate session
  #      if: ${{ always() }}
  #      uses: mxschmitt/action-tmate@v3
