name: LordOS-CI
on:
  pull_request:
    branches: [main]
  schedule: [cron: "0 */4 * * *"]

env:
  CROSS_TOOLCHAIN_PATH: /home/runner/x-tools

jobs:
  build-latest-stable-kernel:
    name: Build latest stable kernel with LLVM 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          curl http://cdn.kernel.org -o kernel.org.html
          sed -n '/<td>stable:<\/td>/I,/<\/tr>/I{ s/<[^>]*>//g; s/\[[^][]*\]//g; p }' kernel.org.html > stable_info.txt
          grep -E "[0-9]+\.[0-9]+" stable_info.txt > stable_versions.txt
          KERNEL_VERSION=`awk 'NR==1 {print $1}' stable_versions.txt`
          echo "To compile kernel $KERNEL_VERSION"
          build/build-kernel.sh
        env:
          LLVM_VERSION: 10
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-previous-stable-kernel:
    name: Build previous stable kernel with LLVM 9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          curl http://cdn.kernel.org -o kernel.org.html
          sed -n '/<td>stable:<\/td>/I,/<\/tr>/I{ s/<[^>]*>//g; s/\[[^][]*\]//g; p }' kernel.org.html > stable_info.txt
          grep -E "[0-9]+\.[0-9]+" stable_info.txt > stable_versions.txt
          KERNEL_VERSION=`awk 'NR==2 {print $1}' stable_versions.txt`
          echo "To compile kernel $KERNEL_VERSION"
          build/build-kernel.sh
        env:
          LLVM_VERSION: 9
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-image:
    name: Build OS image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - run: |
          build/build-os-image.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-lordos-aarch64:
    name: Build LordOS for ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron.yml
          workflow_conclusion: success
          name: aarch64-toolchain
          path: ${{ env.CROSS_TOOLCHAIN_PATH }}
      - name: Compile toolchain
        env:
          ARCH: aarch64
        run: |
          tar -zxvf ~/x-tools/aarch64*.tgz -C ~/x-tools/
          build/build-lordos.sh |& tee $ARCH-build.log
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-lordos-arm:
    name: Build LordOS for ARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron.yml
          workflow_conclusion: success
          name: arm-toolchain
          path: ${{ env.CROSS_TOOLCHAIN_PATH }}
      - name: Compile toolchain
        env:
          ARCH: arm
        run: |
          tar -zxvf ~/x-tools/arm*.tgz -C ~/x-tools/
          build/build-lordos.sh |& tee $ARCH-build.log
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
  build-lordos-x86_64:
    name: Build LordOS for X86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron.yml
          workflow_conclusion: success
          name: x86_64-toolchain
          path: ${{ env.CROSS_TOOLCHAIN_PATH }}
      - name: Compile toolchain
        env:
          ARCH: x86_64
        run: |
          tar -zxvf ~/x-tools/x86_64*.tgz -C ~/x-tools/
          build/build-lordos.sh |& tee $ARCH-build.log
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

