name: CI
on:
  pull_request:
    branches: [main]
  schedule: [cron: "0 */4 * * *"]

jobs:
  build-latest-stable-kernel:
    name: Build latest stable kernel with LLVM 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          build/build-kernel.sh
        env:
          KERNEL_VERSION: 5.9.9
          LLVM_VERSION: 10
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-previous-stable-kernel:
    name: Build previous stable kernel with LLVM 9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile kernel
        run: |
          build/build-kernel.sh
        env:
          KERNEL_VERSION: 5.8.18
          LLVM_VERSION: 9
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-image:
    name: Build OS image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - run: |
          build/build-os-image.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
