name: CRON-XTOOLS
on:
  pull_request:
    branches: [main]
  schedule: [cron: "0 */12 * * *"]

jobs:
  build-xtools-aarch64:
    name: Build toolchain for ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ARCH=aarch64 build/build-toolchain.sh
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64-toolchain
          path: '~/x-tools/aarch64*.tgz'
          if-no-files-found: error
          retention-days: 7
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-xtools-arm:
    name: Build toolchain for ARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ARCH=arm build/build-toolchain.sh
      - uses: actions/upload-artifact@v2
        with:
          name: arm-toolchain
          path: '~/x-tools/arm*.tgz'
          if-no-files-found: error
          retention-days: 7
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-xtools-x86_64:
    name: Build toolchain for X86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ARCH=x86_64 build/build-toolchain.sh
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-toolchain
          path: '~/x-tools/x86_64*.tgz'
          if-no-files-found: error
          retention-days: 7
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  #upload-toolchain:
  #  name: Upload toolchain
  #  needs: [build-xtools-aarch64, build-xtools-arm, build-xtools-x86_64]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/upload-artifact@v2
  #      with:
  #        name: toolchain
  #        path: '~/x-tools/*.tgz'
  #        if-no-files-found: error
  #        retention-days: 7

